import Header from "@/components/header";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const toggleGrid = () => {
    setIsGrid(!isGrid);
  };

  const isGrid = false;

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-full  px-6 py-4">
          <Header />
        </div>
        {children}
      </body>
    </html>
  );
}
