export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS";
export const GET_EMPLOYEES_FAILED = "GET_EMPLOYEES_FAILED";

export const DELETE_EMPLOYEES = "DELETE_EMPLOYEES";
export const DELETE_EMPLOYEES_SUCCESS = "DELETE_EMPLOYEES_SUCCESS";
export const DELETE_EMPLOYEES_FAILED = "DELETE_EMPLOYEES_FAILED";

export const ADD_EMPLOYEES = "ADD_EMPLOYEES";
export const ADD_EMPLOYEES_SUCCESS = "ADD_EMPLOYEES_SUCCESS";
export const ADD_EMPLOYEES_FAILED = "ADD_EMPLOYEES_FAILED";

export const UPDATE_EMPLOYEES = "UPDATE_EMPLOYEES";
export const UPDATE_EMPLOYEES_SUCCESS = "UPDATE_EMPLOYEES_SUCCESS";
export const UPDATE_EMPLOYEES_FAILED = "UPDATE_EMPLOYEES_FAILED";
